### ISSUE TITLE
Maintain Request

### ISSUE THREAD

**Issue by alptugan** [alptugan/ofxTextSuite#15]
Hi Furkan,

I was going to send PR, then noticed your note. I can maintain the repository. I constantly use ofTexSuite in my projects and have modified the code a lot with additional methods/fixes. I can maintain the code if you are still looking for a maintainer.

**Comment by Furkanzmc** [comment]
Hey @alptugan!

Thank you for offering to take ownership! I already created a request for you.

**Comment by alptugan** [comment]
Thank you for the addon! It helps to save time whenever I deal with UI in openframeworks! I'll do my best to keep it alive :)
